### ISSUE TITLE
Create automated tests

### ISSUE THREAD

**Issue by dagwieers** [dagwieers/op#2]
@gits68 Maybe we should consider adding some Travis tests.

**Comment by gits68** [comment]
didn't know until then, I'll see...

**Comment by dagwieers** [comment]
@gits68 I wasn't delegating this to you BTW. I was interested in your opinion on this.
Travis is quite simple to set up and use in our advantage.

**Comment by gits68** [comment]
well, tried it on my repo, it works, for building at least.
later, I'll to build an archive if possible, then to deploy the archive...

https://github.com/gits68/op/blob/master/.travis.yml
don't know if you can access https://travis-ci.org/gits68/op/builds/191483215

**Comment by dagwieers** [comment]
Looking good ! Submit :-)

**Comment by gits68** [comment]
done 5 years later :-) https://travis-ci.org/github/gits68/op
