### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [dagwieers/op#3]
Hi,
I have design this logo with the letter O and P, if you like you can keap it for this project.
If you want it I will give you all the formats of the design free. If you want to make changes please specify.

Greetings

![oplogo-model](https://user-images.githubusercontent.com/34600369/39528353-c55dd8e2-4e1b-11e8-9599-cf2f77a3e89e.png)

**Comment by alecthomas** [comment]
Hi @nunojesus , sorry we didn't reply sooner.

I actually really like the logo, but op is basically unmaintained at this point (I think @dagwieers would agree). So while I like it, I don't think it would be useful to op.

Thanks for thinking of us though!
